// Generated by ChatGPT 4.0
//
#include <stdio.h>
#include <stdlib.h>

double taylor_series_sin(double x, int num_terms) 
{
    double sin_x = 0;
    double term = x;
    for (int n = 1; n <= num_terms; n++) 
    {
        sin_x += term;
        term *= -x * x / ((2 * n) * (2 * n + 1));
    }
    return sin_x;
}

int main() 
{
    double x;
    int num_terms;

    printf("Enter the angle in radians: ");
    scanf("%lf", &x);

    printf("Enter the number of terms in the Taylor series: ");
    scanf("%d", &num_terms);

    double sin_approx = taylor_series_sin(x, num_terms);

    printf("Series sin(x) = %20.16e\n", sin_approx);

    return 0;
}

