// Generated by ChatGPT
//
// Prompted to match cosgpt2.c
//
// Sam Siewert - cleaned up and made sure it matched
//
#include <stdlib.h>
#include <stdio.h>
#include <math.h>

double taylor_series_sin(double x, int num_terms) 
{
    double sin_x = 0;
    double term = x;
    for (int n = 1; n <= num_terms; n++) 
    {
        sin_x += term;
        term *= -x * x / ((2 * n) * (2 * n + 1));
    }
    return sin_x;
}

#define TS_ITERATIONS (1000000)

int main(int argc, char *argv[])
{
    double step = 0.1;
    double max_angle = 8 * 3.14159265358979323846;
    int num_terms = TS_ITERATIONS;

    double sum_squared_diff = 0;
    int num_points = 0;

    if(argc == 1)
    {
        printf("Using default %d iterations\n", TS_ITERATIONS);
    }
    if(argc == 2)
    {
        num_terms = atoi(argv[1]);
        printf("Using default %d iterations\n", num_terms);
    }
    else
    {
        printf("Use: cosgpt [num_terms]\n");
    }

    printf("Angle (radians)\t\tTaylor Series\t\tActual Value\t\tDifference\n");

    for (double x = 0.0; x <= max_angle; x += step) 
    {
        double sin_approx = taylor_series_sin(x, num_terms);
        double sin_actual = sin(x);
        double difference = sin_approx - sin_actual;

        sum_squared_diff += difference * difference;
        num_points++;

        printf("%16.15lf\t%16.15lf\t%16.15lf\t%16.15lf\n", x, sin_approx, sin_actual, difference);
    }

    double mean_squared_error = sum_squared_diff / num_points;
    double root_mean_squared_error = sqrt(mean_squared_error);

    printf("Root Mean Squared Error: %20.15f\n", root_mean_squared_error);

    return 0;
}

