// GENERATED by ChatGPT 4.0 from OpenAI
//
// Prompted by Sam Siewert
//
// To use the program, you'd compile it, and then run it specifying an input and output filename:
//
// gcc program_name.c -o output_name
// ./output_name input.ppm output.ppm
//
// It reads the input PPM file and writes it to the output file unchanged.

#include <stdio.h>
#include <stdlib.h>

typedef struct {
    int width, height, max_val;
    unsigned char *data;
} Image;

Image* read_ppm(const char *filename) {
    FILE *file = fopen(filename, "rb");
    if (!file) {
        perror("Failed to open file");
        exit(1);
    }

    Image *img = (Image *)malloc(sizeof(Image));
    char type[3];
    fscanf(file, "%2s", type);
    if (type[0] != 'P' || type[1] != '6') {
        fprintf(stderr, "Unsupported file format.\n");
        exit(1);
    }
    fgetc(file); // consume newline

    fscanf(file, "%d %d %d", &img->width, &img->height, &img->max_val);
    fgetc(file); // consume newline

    img->data = (unsigned char *)malloc(3 * img->width * img->height * sizeof(unsigned char));
    fread(img->data, 3, img->width * img->height, file);

    fclose(file);
    return img;
}

void write_ppm(const char *filename, Image *img) {
    FILE *file = fopen(filename, "wb");
    if (!file) {
        perror("Failed to open file");
        exit(1);
    }

    fprintf(file, "P6\n%d %d\n%d\n", img->width, img->height, img->max_val);
    fwrite(img->data, 3, img->width * img->height, file);
    
    fclose(file);
}

int main(int argc, char *argv[]) {
    if (argc != 3) {
        fprintf(stderr, "Usage: %s <input.ppm> <output.ppm>\n", argv[0]);
        return 1;
    }

    Image *img = read_ppm(argv[1]);
    write_ppm(argv[2], img);

    free(img->data);
    free(img);

    return 0;
}


