// Generated by Gemini in response to:
// is there a good simple demonstration of the value and use of multiplying two large matrices
// can you generate image blur using C++ and a PGM
// can you fix the code - it only generated a header and no data for the blurred image output
// this code does not read in the following PGM and just returns 1
//
// the final code is here and seems to work fine with a playing card PGM used in class
//
#include <iostream>
#include <vector>
#include <fstream>
#include <string>
#include <sstream>

struct PGMImage {
    int width = 0, height = 0;
    std::vector<unsigned char> data;
};

// Helper to skip comments and whitespace in PGM headers
void skipComments(std::ifstream& f) {
    while (f >> std::ws && f.peek() == '#') {
        std::string dummy;
        std::getline(f, dummy);
    }
}

PGMImage readPGM(const std::string& filename) {
    std::ifstream file(filename, std::ios::binary);
    if (!file.is_open()) {
        std::cerr << "Error: Could not open file " << filename << std::endl;
        return {};
    }

    std::string magic;
    int maxVal;
    PGMImage img;

    // Read magic number (P5)
    if (!(file >> magic) || magic != "P5") {
        std::cerr << "Error: Not a valid P5 PGM file." << std::endl;
        return {};
    }

    // Read width, height, and max value while skipping potential comments
    skipComments(file); file >> img.width;
    skipComments(file); file >> img.height;
    skipComments(file); file >> maxVal;
    
    // Skip the single whitespace character exactly before binary data
    file.ignore(1); 

    if (img.width <= 0 || img.height <= 0) return {};

    img.data.resize(img.width * img.height);
    file.read(reinterpret_cast<char*>(img.data.data()), img.data.size());
    
    return img;
}

void writePGM(const std::string& filename, const PGMImage& img) {
    std::ofstream file(filename, std::ios::binary);
    if (!file) return;
    file << "P5\n" << img.width << " " << img.height << "\n255\n";
    file.write(reinterpret_cast<const char*>(img.data.data()), img.data.size());
}

PGMImage applyBlur(const PGMImage& input) {
    PGMImage output = input;
    int w = input.width;
    int h = input.height;
    if (w < 3 || h < 3) return input;

    for (int y = 1; y < h - 1; ++y) {
        for (int x = 1; x < w - 1; ++x) {
            int sum = 0;
            for (int ky = -1; ky <= 1; ++ky) {
                for (int kx = -1; kx <= 1; ++kx) {
                    sum += input.data[(y + ky) * w + (x + kx)];
                }
            }
            output.data[y * w + x] = static_cast<unsigned char>(sum / 9);
        }
    }
    return output;
}

int main() {
    // Ensure "input.pgm" is in the same folder as your compiled executable
    PGMImage input = readPGM("input.pgm");
    if (input.data.empty()) {
        std::cerr << "Failed to read image data." << std::endl;
        return 1;
    }

    PGMImage blurred = applyBlur(input);
    writePGM("output_blurred.pgm", blurred);
    
    std::cout << "Successfully blurred image (" << input.width << "x" << input.height << ")" << std::endl;
    return 0;
}

